server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false

spring.datasource:
  platform: h2
#  platform: postgres
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:testdb;MODE=PostgreSQL
  #  url: jdbc:postgresql://localhost:5432/mydb
  username: foo
  password: bar

logging:
  level:
    hello: TRACE
    org:
      hibernate:
        SQL: DEBUG
